"""Generate portable pytest checks from a verified reproduction capsule."""

from __future__ import annotations

import pprint
import re
from pathlib import Path

from reproflow.capsule.schema import ReproSpec


def generate_regression_test(
    spec: ReproSpec,
    output: Path,
    *,
    repo_root: Path | None = None,
) -> Path:
    """Write a pytest test that re-runs the capsule through the deterministic verifier.

    The generated test intentionally keeps the capsule embedded in the file.  It therefore
    remains reviewable and does not depend on a hidden generated directory or mutable state.
    Docker and the ReproFlow package are the only runtime dependencies, matching the normal
    ``reproflow run`` path.
    """
    output = output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    payload = pprint.pformat(
        spec.model_dump(mode="json", by_alias=True), width=100, sort_dicts=False
    )
    function_name = "test_reproflow_" + _safe_identifier(spec.metadata.id)

    if repo_root is None:
        source_expression = "None"
    else:
        root = repo_root.resolve()
        try:
            relative_parent = output.parent.relative_to(root)
        except ValueError:
            source_expression = f"Path({str(root)!r})"
        else:
            depth = len(relative_parent.parts)
            source_expression = f"Path(__file__).resolve().parents[{depth}]"

    content = f'''"""Generated by ReproFlow; keep this test under version control."""

from pathlib import Path

from reproflow.capsule.schema import ReproSpec
from reproflow.sandbox.docker import DockerSandboxRunner
from reproflow.verifier.verifier import Verifier


def {function_name}() -> None:
    spec = ReproSpec.model_validate({payload})
    result = Verifier(DockerSandboxRunner(source_root={source_expression})).verify(spec)
    assert result.reproduced, (
        f"ReproFlow regression no longer reproduces: "
        f"{{result.successful_runs}}/{{result.total_runs}} matched; "
        f"signature={{result.stable_signature or 'none'}}"
    )
'''
    output.write_text(content, encoding="utf-8")
    return output


def _safe_identifier(value: str) -> str:
    value = re.sub(r"[^A-Za-z0-9_]+", "_", value).strip("_")
    if not value:
        value = "capsule"
    if value[0].isdigit():
        value = "capsule_" + value
    return value[:100]
