from __future__ import annotations

import re
import shlex
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True, slots=True)
class RegressionTest:
    output_path: Path
    command: str
    source_capsule: Path


def _read_command(capsule: Path) -> str:
    json_candidate = capsule / "repro.json"
    if json_candidate.exists():
        import json

        data = json.loads(json_candidate.read_text(encoding="utf-8"))
        command = data.get("run", {}).get("command") or data.get("command")
        if isinstance(command, str) and command.strip():
            return command.strip()

    yaml_candidate = capsule / "repro.yaml"
    if yaml_candidate.exists():
        text = yaml_candidate.read_text(encoding="utf-8")
        # Accept common forms: command: python repro.py / command: "python repro.py"
        match = re.search(r"(?m)^\s*command:\s*(.+?)\s*$", text)
        if match:
            value = match.group(1).strip()
            if len(value) >= 2 and value[0] == value[-1] and value[0] in {'\"', "'"}:
                value = value[1:-1]
            if value:
                return value

    for candidate in ("reproduce.sh", "repro.py", "reproduce.py"):
        if (capsule / candidate).exists():
            if candidate.endswith(".sh"):
                return f"bash {shlex.quote(candidate)}"
            return f"python {shlex.quote(candidate)}"

    raise FileNotFoundError(
        "Could not determine reproduction command. Expected repro.json, repro.yaml, "
        "reproduce.sh, repro.py, or reproduce.py in the capsule."
    )


def _safe_test_name(issue: str) -> str:
    value = re.sub(r"[^a-zA-Z0-9_]+", "_", issue).strip("_").lower()
    return value or "reproduction"


def generate_regression_test(
    capsule: str | Path,
    output: str | Path,
    *,
    issue: str = "reproduction",
) -> RegressionTest:
    capsule_path = Path(capsule).resolve()
    if not capsule_path.is_dir():
        raise NotADirectoryError(capsule_path)
    command = _read_command(capsule_path)
    output_path = Path(output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    test_name = _safe_test_name(issue)

    content = f'''"""Generated by ReproFlow Alpha 5.

This regression test executes the verified reproduction capsule. Before the
bug is fixed the command should exit non-zero; after the fix it should pass.
"""

from __future__ import annotations

import subprocess
from pathlib import Path


def test_{test_name}() -> None:
    capsule = Path({str(capsule_path)!r})
    result = subprocess.run(
        {command!r},
        cwd=capsule,
        shell=True,
        text=True,
        capture_output=True,
        timeout=60,
    )
    assert result.returncode == 0, (
        "Verified reproduction still fails.\\n"
        f"command: {command}\\n"
        f"exit_code: {{result.returncode}}\\n"
        f"stdout:\\n{{result.stdout}}\\n"
        f"stderr:\\n{{result.stderr}}"
    )
'''
    output_path.write_text(content, encoding="utf-8")
    return RegressionTest(output_path=output_path, command=command, source_capsule=capsule_path)
